sudo: false
language: node_js
node_js:
- '6'
- '8'
install:
- npm i npminstall && npminstall
script:
- npm run ci
after_script:
- npminstall codecov && codecov
before_install:
- openssl aes-256-cbc -K $encrypted_336e653e42ec_key -iv $encrypted_336e653e42ec_iv
  -in travis.enc -out ~\/travis -d
